- name: Install K3s 
  shell: curl -sfL https://get.k3s.io | sh -
  become: yes 
  environment:
    K3S_KUBECONFIG_MODE: "644"
    INSTALL_K3S_EXEC: " --no-deploy servicelb --no-deploy traefik" 
  when: '"k3s" not in ansible_facts.services'
    
- name: Register K3s leader node token 
  command: cat /var/lib/rancher/k3s/server/node-token
  become: yes 
  register: k3s_token 
    
- name: "Add K3S leader variables to dummy host"
  add_host:
    name:   "K3S_LEADER"
    token:  "{{ k3s_token.stdout }}"
    ip: "{{ ansible_default_ipv4.address }}"