- name: Populate service facts
  service_facts:

- name: Gather package facts
  package_facts:
    manager: apt

- name: Install chrony to sync clock
  become: yes
  apt:
    pkg:
      - chrony
  when: '"chrony" not in ansible_facts.packages'

- name: Start the chrony service
  become: yes
  service: 
    name: chrony
    state: started
  when: '"chrony" not in ansible_facts.services'

- name: Check cmdline.txt
  command: grep -Fxq "cgroup" /boot/firmware/cmdline.txt
  register: check_cmdline
  check_mode: no
  ignore_errors: yes
  changed_when: no

# Enable cgroup 
# - name: Copy cmdline.txt 
#   become: yes
#   copy:
#     src: ../templates/cmdline.txt
#     dest: /boot/firmware/cmdline.txt
#   when: check_cmdline is failed

# Make sure we're running in 64bit mode
# - name: Check if arm_64bit=1 already exists in the file
#   shell: "grep -q '^arm_64bit=1$' /boot/firmware/config.txt"
#   register: check_64bit 
#   ignore_errors: true

# - name: Add arm_64bit=1 to the file if not present
#   block:
#     - name: Append arm_64bit=1 to config.txt
#       lineinfile:
#         path: /boot/firmware/config.txt
#         line: "arm_64bit=1"
#         insertafter: EOF
#       when: check_64bit.rc != 0
#   when: check_64bit is failed

# - name: Reboot for cmdline.txt updates 
#   become: yes
#   reboot:
#     reboot_timeout: 600
#   when: check_cmdline.rc == 0 or check_64bit.rc == 0
