- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

# https://docs.k3s.io/installation/requirements?os=debian#operating-systems
- name: Disable ufw
  become: yes
  community.general.ufw:
    state: disabled

- name: Enable legacy iptables
  become: yes
  command: update-alternatives --set iptables /usr/sbin/iptables-legacy