- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

# https://docs.k3s.io/installation/requirements?os=debian#operating-systems
- name: Disable ufw
  become: yes
  community.general.ufw:
    state: disabled

- name: Enable legacy iptables
  become: yes
  command: update-alternatives --set iptables /usr/sbin/iptables-legacy

- name: Install Docker prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent

- name: Add Docker's official GPG key
  become: yes
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Set up the Docker stable repository
  become: yes
  ansible.builtin.shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update apt package list (again)
  become: yes
  apt: 
    update_cache: yes

- name: Install Docker
  become: yes
  apt:
    name: docker
    state: present
  