- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

# https://docs.k3s.io/installation/requirements?os=debian#operating-systems
- name: Disable ufw
  become: yes
  community.general.ufw:
    state: disabled

- name: Enable legacy iptables
  become: yes
  command: update-alternatives --set iptables /usr/sbin/iptables-legacy

# Docker
- name: Install required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Add Docker's official GPG key
  become: yes
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add Docker apt repository
  become: yes
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache (again)
  become: yes
  apt:
    update_cache: yes

- name: Install Docker and related packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin


- name: Add user to docker group
  become: yes
  shell: |
    if ! getent group docker > /dev/null; then
      groupadd docker
      usermod -aG docker {{ ansible_user }}
      newgrp docker
    fi
