---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add Nginx reverse proxy configuration
  copy:
    src: ../templates/nginx.conf 
    dest: /etc/nginx/sites-available/reverse-proxy.conf

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted