- name: Install K3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--prefer-bundled-bin --disable=traefik --disable=servicel" sh -s -
  become: yes
  environment:
    K3S_KUBECONFIG_MODE: "644"
    K3S_URL: "https://{{ hostvars['K3S_LEADER']['host_name'] }}:6443"
    K3S_TOKEN: "{{ hostvars['K3S_LEADER']['token'] }}"
    K3S_NODE_NAME: "{{ inventory_hostname }}"