- hosts: all

- name: Include leader play
  import_playbook: leader.yml

- name: Include workers play
  import_playbook: workers.yml

- name: Include public worker play
  import_playbook: droplet.yml
