- name: Update hostname
  become: yes
  copy:
    content: 'kube-master'
    dest: /etc/hostname

- name: Update host file 
  become: yes
  lineinfile:
    path: /etc/hostname
    line: 127.0.1.1       kube-master
    create: yes

- name: Install K3s
  shell: curl -sfL https://get.k3s.io | sh -
  become: yes 
  environment:
    K3S_KUBECONFIG_MODE: "644"
    INSTALL_K3S_EXEC: " --no-deploy servicelb --no-deploy traefik" 
  when: '"k3s" not in ansible_facts.services'
    
- name: Register K3s leader node token 
  command: cat /var/lib/rancher/k3s/server/node-token
  become: yes 
  register: k3s_token

- name: Replace a localhost entry with actual IP
  become: yes
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: '127.0.0.1'
    replace: "{{ ansible_default_ipv4.address }}"
    backup: yes

- name: Copy kubeconfig contents
  command: "cat /etc/rancher/k3s/k3s.yaml"
  register: kubeconfig_contents
    
- name: "Add K3S leader variables to dummy host"
  become: yes
  add_host:
    name:   "K3S_LEADER"
    token:  "{{ k3s_token.stdout }}"
    ip: "{{ ansible_default_ipv4.address }}"
    kubeconfig: "{{ kubeconfig_contents.stdout }}"
